feat: add a dockerfile for running in gcp cloud build
nitrictech/cli pull request #213
Opened 2022-04-10 23:58 UTC by asalkeld

2022-05-02 23:06 UTC, davemooreuws approved these changes

2022-05-03 01:14 UTC, tjholm requested changes

2022-05-03 01:14 UTC, tjholm commented on Makefile
> +	docker manifest push asalkeld/nitric-cli:latest
@asalkeld take a look at https://github.com/nitrictech/boxygen/blob/develop/.github/workflows/publish-images.yaml

For the image publish to our nitrictech dockerhub repository.

2022-05-10 03:55 UTC, tjholm approved these changes

2022-05-10 04:29 UTC, merged