Release
nitrictech/cli pull request #533
Opened 2023-06-29 02:43 UTC by tjholm

2023-06-29 02:55 UTC, HomelessDinosaur approved these changes, later dismissed

2023-06-29 02:57 UTC, davemooreuws requested changes
Should bump the default nitric version? Currently 0.27

2023-06-29 04:03 UTC, davemooreuws approved these changes, later dismissed

2023-06-29 05:12 UTC, tjholm commented on pkg/runtime/typescript.dockerfile
> +COPY --from=build node_modules/ ./node_modules/
Need to verify this change (the copy of the json/lock files above are actually being copied into the container root

2023-06-30 00:42 UTC, HomelessDinosaur approved these changes

2023-06-30 00:57 UTC, davemooreuws approved these changes

2023-07-02 23:48 UTC, jyecusch approved these changes

2023-07-02 23:49 UTC, merged