feat: update start and run commands to use bubble tea styling
nitrictech/cli pull request #593
Opened 2023-10-12 22:30 UTC by HomelessDinosaur

2023-10-31 23:09 UTC, jyecusch commented
I'm seeing some odd behaviour when resizing the terminal

![image](https://github.com/nitrictech/cli/assets/4121391/6962ef38-7d94-4eee-bbb1-b1e3f1b3126a)

2023-11-12 23:32 UTC, tjholm approved these changes, later dismissed

2023-11-13 00:16 UTC, davemooreuws commented
I can see two quit messages at end of `nitric run`

![image](https://github.com/nitrictech/cli/assets/4121492/179970fd-1d52-4032-a467-b4cb1055cb30)

2023-11-13 00:21 UTC, davemooreuws commented
Don't start browser until a stack is found (see screenshot). Like the current behavior. 
![image](https://github.com/nitrictech/cli/assets/4121492/f26d8399-8aae-4b34-a20a-7663f0d920be)

2023-11-13 07:09 UTC, davemooreuws requested changes

2023-11-13 07:09 UTC, davemooreuws commented on pkg/tui/localservices/localservices.go
> +			err = dash.Serve(ls.GetStorageService(), noBrowser || output.CI)
This runs twice on the run command now. Causing an error.

2023-11-13 07:09 UTC, davemooreuws commented on pkg/tui/buildlog/help.go
> +		key.WithHelp("q", "quit"),
shall we change quit to esc to mirror the new project command?

2023-11-14 04:04 UTC, davemooreuws approved these changes

2023-11-14 04:05 UTC, davemooreuws commented
Approved. Lets take note of persisting the build log for v1/new PR

2023-11-14 04:20 UTC, tjholm approved these changes

2023-11-14 05:37 UTC, merged