update collections references to kv
nitrictech/cli pull request #677
Opened 2024-02-19 07:00 UTC by jyecusch

2024-02-19 07:26 UTC, davemooreuws requested changes
Looks good, just an issue with the README

2024-02-19 07:26 UTC, davemooreuws commented on README.md
> +c.
typo? Looks like Getting started got duplicated here

2024-02-20 02:10 UTC, tjholm approved these changes

2024-02-20 02:13 UTC, davemooreuws approved these changes

2024-02-20 02:20 UTC, merged