feat: add expiry and operation handling for signed urls.
nitrictech/cli pull request #712
Opened 2024-04-11 02:35 UTC by tjholm

Adds expiring handling and locks in file and operations for upload and download operations.

2024-04-11 02:50 UTC, HomelessDinosaur requested changes

2024-04-11 02:50 UTC, HomelessDinosaur commented on pkg/cloud/storage/storage.go
> +func tokenFromRequset(req *storagepb.StoragePreSignUrlRequest) *jwt.Token {
```suggestion
func tokenFromRequest(req *storagepb.StoragePreSignUrlRequest) *jwt.Token {
```

2024-04-11 02:50 UTC, HomelessDinosaur commented on pkg/cloud/storage/storage.go
> +
```suggestion
```

2024-04-11 02:50 UTC, HomelessDinosaur commented on pkg/cloud/storage/storage.go
> +	token := tokenFromRequset(req)
```suggestion
	token := tokenFromRequest(req)
```

2024-04-11 05:24 UTC, HomelessDinosaur approved these changes

2024-04-12 03:54 UTC, jyecusch approved these changes

2024-04-12 03:55 UTC, merged