fix: add dashboard alert for security rules in api explorer
nitrictech/cli pull request #719
Opened 2024-04-15 01:41 UTC by davemooreuws

also adds security definition to exported spec

2024-04-15 02:18 UTC, HomelessDinosaur commented on pkg/dashboard/frontend/src/components/apis/APIExplorer.tsx
> +                          nitric for local development.
```suggestion
                          Nitric for local development.
```

2024-04-15 02:21 UTC, HomelessDinosaur commented on pkg/dashboard/frontend/src/components/apis/APIExplorer.tsx
> +                  <Alert>
Can the alert by a warning yellow? the white is difficult to see.

2024-04-15 05:12 UTC, HomelessDinosaur approved these changes, later dismissed

2024-04-19 03:06 UTC, tjholm requested changes, later dismissed

2024-04-19 03:06 UTC, tjholm commented on cmd/stack.go
> +		envVariables, err := env.ReadLocalEnv()
disabling the --env-file args?

2024-04-19 03:32 UTC, HomelessDinosaur approved these changes

2024-04-22 05:35 UTC, jyecusch approved these changes

2024-04-22 06:12 UTC, merged