feat: Initial SQL support
nitrictech/cli pull request #732
Opened 2024-05-14 04:20 UTC by tjholm

Add support for collecting SQL database requirements and building migrations.

2024-05-16 04:09 UTC, davemooreuws approved these changes, later dismissed
Works great. Only thing is `nitric start` does not show any progress when pulling postgres locally.

2024-06-04 00:47 UTC, tjholm commented
> Works great. Only thing is `nitric start` does not show any progress when pulling postgres locally.

Have implemented a quick version of this with a simple `Starting Local Cloud` message.

2024-06-05 04:22 UTC, davemooreuws submitted a review, later dismissed

2024-06-05 04:37 UTC, davemooreuws requested changes

2024-06-05 04:37 UTC, davemooreuws commented on pkg/cloud/sql/sql.go
> +		// TODO: Randomize instance name to allow multiple starts
```suggestion
```

2024-06-05 04:37 UTC, davemooreuws commented on pkg/cloud/sql/sql.go
> +			// TODO: Randomize port number to allow multiple starts
```suggestion
```

2024-06-05 05:08 UTC, davemooreuws approved these changes

2024-06-11 01:29 UTC, HomelessDinosaur approved these changes

2024-06-11 01:30 UTC, merged