feat: add terraform provider to new stack prompts
nitrictech/cli pull request #738
Opened 2024-06-18 03:50 UTC by jyecusch

2024-06-18 14:23 UTC, raksiv submitted a review, later dismissed

2024-06-18 22:33 UTC, davemooreuws requested changes

2024-06-18 22:33 UTC, davemooreuws commented on pkg/project/stack/awstf.config.yaml
> +provider: nitric/awstf@1.6.1
```suggestion
provider: nitric/awstf@1.6.2
```

2024-06-18 22:33 UTC, davemooreuws commented on pkg/project/stack/awstf.config.yaml
> +# Optional Configuration Below
Double check how much of this config is actually supported.

2024-06-19 01:36 UTC, davemooreuws approved these changes

2024-06-21 03:15 UTC, tjholm approved these changes

2024-06-21 03:16 UTC, merged