fix schedules and batch docs links
nitrictech/cli pull request #790
Opened 2024-10-04 01:25 UTC by jyecusch

2024-10-04 01:29 UTC, davemooreuws approved these changes

2024-10-04 02:01 UTC, davemooreuws requested changes

2024-10-04 02:01 UTC, davemooreuws commented on pkg/dashboard/frontend/src/components/events/EventsExplorer.tsx
> +  topics: 'topics',
```suggestion
  topics: 'messaging',
```

2024-10-04 02:01 UTC, davemooreuws commented on pkg/dashboard/frontend/src/components/events/EventsExplorer.tsx
> +  topics: 'topics',
topics isn't a valid link

2024-10-14 02:54 UTC, davemooreuws approved these changes

2024-10-15 00:08 UTC, HomelessDinosaur approved these changes

2024-10-15 00:08 UTC, merged